### ISSUE TITLE
Overwriting Is Triggered by Close Button in Save-As Dialog 

### ISSUE THREAD

**Issue by mahsashadi** [os-js/osjs-dialogs#11]
Hi.
I think there is a bug  when I close the save-as dialog by close button (not by cancel button). If the filename textbox has some value, the confirm dialog for overwriting is triggered by pressing close button!
For example It happenes in your textpad application.

**Comment by andersevenrud** [comment]
I've released a new version of `@osjs/dialogs` that should solve this issue.
