### ISSUE TITLE
Question on desired color dialog behavior

### ISSUE THREAD

**Issue by ajmeese7** [os-js/osjs-dialogs#14]
By default the color dialog only changes the hex of the textbox once the user has let go of the slider, not showing them a preview as they drag. On my implementation I have merged `onchange` into `oninput` so the hex is updated as the user slides, so they know what the color looks like before they release.

I could make a quick PR for this if you are interested, but I don't know if you prefer the current behavior as opposed to the behavior that I mentioned.

**Comment by andersevenrud** [comment]
> I could make a quick PR for this if you are interested

Sure!
