### ISSUE TITLE
save file dialog OK button enabled when no directory selected

### ISSUE THREAD

**Issue by Dorosty** [os-js/osjs-dialogs#20]
why is this line like this?
https://github.com/os-js/osjs-dialogs/blob/66f8aa53856279e43b5d4dcc557b8270ad374c1e/src/dialogs/file.js#L129-L133

shouldn't it just be?
```js
buttons: {
  ok: !!this.args.filename
}
```

Currently whenever the save dialog box is opened with `filetype: 'directory'` the OK button is enabled. Which may be wrong.

**Comment by andersevenrud** [comment]
Feel free to submit a PR to change the behavior :)
