### ISSUE TITLE
Not displaying the Internet connection Lost notification in Chrome.

### ISSUE THREAD

**Issue by maryam4s26** [os-js/osjs-dialogs#24]
hi @andersevenrud .
When the server crashes or down, we receive a disconnection notification in all browsers.

![image](https://github.com/os-js/osjs-dialogs/assets/65979871/c9bf6592-482a-4a50-85aa-4b88f1dca709)

But when the internet is interrupted, Chrome browser does not receive this notification, but we receive this notification in other browsers.

**Comment by andersevenrud** [comment]
This notification comes from when the websocket closes unexpectedly: https://github.com/os-js/osjs-client/blob/f4343b818274a2823ea8e28b0fbb816b2e9c23e9/src/core.js#L409 via https://github.com/os-js/osjs-client/blob/f4343b818274a2823ea8e28b0fbb816b2e9c23e9/src/websocket.js#L180

Does the websocket go down in Chrome ?

**Comment by maryam4s26** [comment]
I apologize.
This issue has not been opened in the right place and belongs here.
I close this issue and open https://github.com/os-js/osjs-client/issues/214.

**Comment by maryam4s26** [comment]
I apologize.
This issue has not been opened in the right place and belongs here.
I close this issue and open https://github.com/os-js/osjs-client/issues/214.

**Comment by andersevenrud** [comment]
> This issue has not been opened in the right place and belongs here.

No worries. I can actually move these so you don't have to close and re-create. Just let me know when you need that to be done :)

**Comment by maryam4s26** [comment]
Hello @andersevenrud , sorry, I created this [issue](https://github.com/os-js/osjs-client/issues/214) before I saw your comment. :(

**Comment by maryam4s26** [comment]
hi @andersevenrud .Unfortunately, I am confused and do not understand what you mean.
When my internet is interrupted, Google Chrome does not show the server connection notification.
