### ISSUE TITLE
Issue with Cancel button on Save Dialog

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-dialogs#6]
I am using the below code for creating and acting on a Save Dialog in OSjs.

```javascript
    core.make('osjs/dialog', 'file', {type: 'save', title: "Save As"},  {parent: win, attributes: {modal: true}}, (status, file, event) => {
      if (status === "ok") {
        if (!file.path.endsWith(".wf"))
          file.path += ".wf";
        basic.emit('save-file', file);
      }
    });
```

And the resulting Dialog:

![image](https://user-images.githubusercontent.com/29079278/63195716-6451cb00-c041-11e9-9c51-3268ea8c1079.png)

At this point, I would expect clicking the Cancel button to trigger a callback with status = 'cancel' and file = null. However the Cancel button callback doesn't trigger until Filename is populated with some text.

There also appears to be an error handler that triggers if the text equals an existing filename, even if the Cancel button was pressed and not the OK button, example below:

![image](https://user-images.githubusercontent.com/29079278/63197060-c9f38680-c044-11e9-8127-90f0674a1f3f.png)

Pressing No returns to the Save Dialog, and pressing Yes on the Confirm window closes the Save Dialog and sends the status = 'cancel' callback. 

I believe expected behavior is to not display the Confirm dialog when Cancel is pressed and to simply close the Save Dialog while sending the 'cancel' callback, regardless of whether any text is input in the Filename field.

Thanks Anders, you're the man.

**Comment by andersevenrud** [comment]
I've pushed a new release that should fix the following conditions:

1. Pressing `Cancel` on a save dialog with empty field produces no closure
2. Pressing `Cancel` will check for existence instead of closure

Run `npm update @osjs/dialogs` and `npm run build` to update.

Let me know if this takes care of this issue and close it :)

**Comment by andersevenrud** [comment]
In hindsight this was kind of a silly mistake. The `Cancel` button was never actually accounted for in the callback function, so this should fix any side-effects relating to pushing that button.

I really need to get started on adding tests here as I've done in all other libraries related to this project :blush:

**Comment by andersevenrud** [comment]
Just doing a ping since it's been almost a week since you opened this issue :innocent:

**Comment by josephjeno** [comment]
Ah my bad, yes it's been working perfecto! Thanks Anders!
